import { Injectable } from '@nestjs/common';
import { CreateUserDto } from './dto/create-user.dto';
import { UpdateUserDto } from './dto/update-user.dto';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { User } from './entities/user.entity';
import { JwtService } from './jwt.service';
import bcrypt from 'bcryptjs';
import { Booking } from 'src/bookings/entities/booking.entity';

@Injectable()
export class UsersService {
  constructor(
    private jwtService: JwtService,
    @InjectRepository(User)
    private userRepository: Repository<User>,
  ) {}
  async create(createUserDto: CreateUserDto) {
    const user = this.userRepository.create(createUserDto);
    return await this.userRepository.save(user);
  }

  findAll() {
    return this.userRepository.find();
  }

  async findOne(id: number) {
    return await this.userRepository.findOneBy({ id });
  }

  async findTicketsUser(id: number): Promise<Booking[] | undefined> {
    const result = await this.userRepository
      .createQueryBuilder('user')
      .leftJoinAndSelect('user.bookings', 'booking')
      .leftJoinAndSelect('booking.tickets', 'ticket')
      .leftJoinAndSelect('booking.busSchedule', 'bus_schedule')
      .leftJoinAndSelect('bus_schedule.schedule', 'schedule')
      .leftJoinAndSelect('schedule.route', 'route')
      .leftJoinAndSelect('bus_schedule.bus', 'bus')
      .where('user.id = :id', { id })
      .getOne();

    return result?.bookings;
  }

  register = async (newUser: CreateUserDto) => {
    const { email, password } = newUser;
    const existingUser = await this.userRepository.findOneBy({ email });
    if (existingUser) {
      throw new Error('User already exists');
    }

    newUser.password = await bcrypt.hash(password, 10);
    const user = this.userRepository.create(newUser);

    // Save the user first so the primary key (`id`) is generated by the DB
    await this.userRepository.save(user);

    // Now generate tokens using the saved user (with `id`)
    const { accessToken, refreshToken } = this.jwtService.generateTokens(user);

    // Persist refresh token
    user.refresh_token = refreshToken;
    await this.userRepository.save(user);

    const user_id = user.id;
    console.log('USER_ID', user);

    return { user_id, accessToken, refreshToken };
  };

  login = async (email: string, password: string) => {
    const user = await this.userRepository.findOneBy({ email });

    if (!user || !(await bcrypt.compare(password, user.password))) {
      throw new Error('Invalid credentials');
    }

    const { accessToken, refreshToken } = this.jwtService.generateTokens(user);

    user.refresh_token = refreshToken;

    await this.userRepository.save(user);

    return {
      user_id: user?.id,
      accessToken,
      refreshToken,
      isAdmin: user.role_id === 1,
      isBlocked: user.is_blocked,
    };
  };

  logout = async (refresh_token: string) => {
    const user = await this.userRepository.findOne({
      where: { refresh_token },
    });
    if (user) {
      user.refresh_token = '';
      await this.userRepository.save(user);
    }
  };

  async update(id: number, updateUserDto: UpdateUserDto) {
    const user = await this.userRepository.findOneBy({ id });
    if (!user) return null;

    const { password } = updateUserDto;

    updateUserDto.password = await bcrypt.hash(String(password), 10);

    await this.userRepository.update(id, updateUserDto);
    return await this.userRepository.findOneBy({ id });
  }

  async remove(id: number) {
    const result = await this.userRepository.delete(id);
    return result.affected !== 0;
  }
}
