import { MigrationInterface, QueryRunner } from 'typeorm';

export class InsertBuses1778373938093 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
            INSERT INTO Buses (bus_number, capacity, type, available) VALUES
('BY1001', ARRAY(SELECT generate_series(1, 20)), 'Mercedes Sprinter', FALSE),
('BY1002', ARRAY(SELECT generate_series(1, 18)), 'Ford Transit', FALSE),
('BY1003', ARRAY(SELECT generate_series(1, 22)), 'Volkswagen Crafter', FALSE),
('BY1004', ARRAY(SELECT generate_series(1, 19)), 'Iveco Daily', FALSE),
('BY1005', ARRAY(SELECT generate_series(1, 21)), 'Peugeot Boxer', FALSE),
('BY1006', ARRAY(SELECT generate_series(1, 20)), 'Mercedes Sprinter', FALSE),
('BY1007', ARRAY(SELECT generate_series(1, 17)), 'Fiat Ducato', FALSE),
('BY1008', ARRAY(SELECT generate_series(1, 23)), 'Volkswagen Crafter', FALSE),
('BY1009', ARRAY(SELECT generate_series(1, 18)), 'Ford Transit', FALSE),
('BY1010', ARRAY(SELECT generate_series(1, 21)), 'Iveco Daily', FALSE),
('BY1011', ARRAY(SELECT generate_series(1, 19)), 'Peugeot Boxer', FALSE),
('BY1012', ARRAY(SELECT generate_series(1, 20)), 'Mercedes Sprinter', FALSE),
('BY1013', ARRAY(SELECT generate_series(1, 16)), 'Citroen Jumper', FALSE),
('BY1014', ARRAY(SELECT generate_series(1, 22)), 'MAN TGE', FALSE),
('BY1015', ARRAY(SELECT generate_series(1, 18)), 'Ford Transit', FALSE),
('BY1016', ARRAY(SELECT generate_series(1, 20)), 'Mercedes Sprinter', FALSE),
('BY1017', ARRAY(SELECT generate_series(1, 17)), 'Volkswagen Crafter', FALSE),
('BY1018', ARRAY(SELECT generate_series(1, 21)), 'Iveco Daily', FALSE),
('BY1019', ARRAY(SELECT generate_series(1, 19)), 'Peugeot Boxer', FALSE),
('BY1020', ARRAY(SELECT generate_series(1, 20)), 'Fiat Ducato', FALSE),
('BY1021', ARRAY(SELECT generate_series(1, 20)), 'Mercedes Sprinter', FALSE),
('BY1022', ARRAY(SELECT generate_series(1, 18)), 'Ford Transit', FALSE),
('BY1023', ARRAY(SELECT generate_series(1, 22)), 'Volkswagen Crafter', FALSE),
('BY1024', ARRAY(SELECT generate_series(1, 19)), 'Iveco Daily', FALSE),
('BY1025', ARRAY(SELECT generate_series(1, 21)), 'Peugeot Boxer', FALSE),
('BY1026', ARRAY(SELECT generate_series(1, 20)), 'Mercedes Sprinter', FALSE),
('BY1027', ARRAY(SELECT generate_series(1, 17)), 'Fiat Ducato', FALSE),
('BY1028', ARRAY(SELECT generate_series(1, 23)), 'Volkswagen Crafter', FALSE),
('BY1029', ARRAY(SELECT generate_series(1, 18)), 'Ford Transit', FALSE),
('BY1030', ARRAY(SELECT generate_series(1, 21)), 'Iveco Daily', FALSE),
('BY1031', ARRAY(SELECT generate_series(1, 19)), 'Peugeot Boxer', FALSE),
('BY1032', ARRAY(SELECT generate_series(1, 20)), 'Mercedes Sprinter', FALSE),
('BY1033', ARRAY(SELECT generate_series(1, 16)), 'Citroen Jumper', FALSE),
('BY1034', ARRAY(SELECT generate_series(1, 22)), 'MAN TGE', FALSE),
('BY1035', ARRAY(SELECT generate_series(1, 18)), 'Ford Transit', FALSE),
('BY1036', ARRAY(SELECT generate_series(1, 20)), 'Mercedes Sprinter', FALSE),
('BY1037', ARRAY(SELECT generate_series(1, 17)), 'Volkswagen Crafter', FALSE),
('BY1038', ARRAY(SELECT generate_series(1, 21)), 'Iveco Daily', FALSE),
('BY1039', ARRAY(SELECT generate_series(1, 19)), 'Peugeot Boxer', FALSE),
('BY1040', ARRAY(SELECT generate_series(1, 20)), 'Fiat Ducato', FALSE),
('BY1041', ARRAY(SELECT generate_series(1, 20)), 'Mercedes Sprinter', FALSE),
('BY1042', ARRAY(SELECT generate_series(1, 18)), 'Ford Transit', FALSE),
('BY1043', ARRAY(SELECT generate_series(1, 22)), 'Volkswagen Crafter', FALSE),
('BY1044', ARRAY(SELECT generate_series(1, 19)), 'Iveco Daily', FALSE),
('BY1045', ARRAY(SELECT generate_series(1, 21)), 'Peugeot Boxer', FALSE),
('BY1046', ARRAY(SELECT generate_series(1, 20)), 'Mercedes Sprinter', FALSE),
('BY1047', ARRAY(SELECT generate_series(1, 17)), 'Fiat Ducato', FALSE),
('BY1048', ARRAY(SELECT generate_series(1, 23)), 'Volkswagen Crafter', FALSE),
('BY1049', ARRAY(SELECT generate_series(1, 18)), 'Ford Transit', FALSE),
('BY1050', ARRAY(SELECT generate_series(1, 21)), 'Iveco Daily', FALSE),
('BY1051', ARRAY(SELECT generate_series(1, 19)), 'Peugeot Boxer', FALSE),
('BY1052', ARRAY(SELECT generate_series(1, 20)), 'Mercedes Sprinter', FALSE),
('BY1053', ARRAY(SELECT generate_series(1, 16)), 'Citroen Jumper', FALSE),
('BY1054', ARRAY(SELECT generate_series(1, 22)), 'MAN TGE', FALSE),
('BY1055', ARRAY(SELECT generate_series(1, 18)), 'Ford Transit', FALSE),
('BY1056', ARRAY(SELECT generate_series(1, 20)), 'Mercedes Sprinter', FALSE),
('BY1057', ARRAY(SELECT generate_series(1, 17)), 'Volkswagen Crafter', FALSE),
('BY1058', ARRAY(SELECT generate_series(1, 21)), 'Iveco Daily', FALSE),
('BY1059', ARRAY(SELECT generate_series(1, 19)), 'Peugeot Boxer', FALSE),
('BY1060', ARRAY(SELECT generate_series(1, 20)), 'Fiat Ducato', FALSE),
('BY1061', ARRAY(SELECT generate_series(1, 20)), 'Mercedes Sprinter', FALSE),
('BY1062', ARRAY(SELECT generate_series(1, 18)), 'Ford Transit', FALSE),
('BY1063', ARRAY(SELECT generate_series(1, 22)), 'Volkswagen Crafter', FALSE),
('BY1064', ARRAY(SELECT generate_series(1, 19)), 'Iveco Daily', FALSE),
('BY1065', ARRAY(SELECT generate_series(1, 21)), 'Peugeot Boxer', FALSE),
('BY1066', ARRAY(SELECT generate_series(1, 20)), 'Mercedes Sprinter', FALSE),
('BY1067', ARRAY(SELECT generate_series(1, 17)), 'Fiat Ducato', FALSE),
('BY1068', ARRAY(SELECT generate_series(1, 23)), 'Volkswagen Crafter', FALSE),
('BY1069', ARRAY(SELECT generate_series(1, 18)), 'Ford Transit', FALSE),
('BY1070', ARRAY(SELECT generate_series(1, 21)), 'Iveco Daily', FALSE),
('BY1071', ARRAY(SELECT generate_series(1, 19)), 'Peugeot Boxer', FALSE),
('BY1072', ARRAY(SELECT generate_series(1, 20)), 'Mercedes Sprinter', FALSE),
('BY1073', ARRAY(SELECT generate_series(1, 16)), 'Citroen Jumper', FALSE),
('BY1074', ARRAY(SELECT generate_series(1, 22)), 'MAN TGE', FALSE),
('BY1075', ARRAY(SELECT generate_series(1, 18)), 'Ford Transit', FALSE),
('BY1076', ARRAY(SELECT generate_series(1, 20)), 'Mercedes Sprinter', FALSE),
('BY1077', ARRAY(SELECT generate_series(1, 17)), 'Volkswagen Crafter', FALSE),
('BY1078', ARRAY(SELECT generate_series(1, 21)), 'Iveco Daily', FALSE),
('BY1079', ARRAY(SELECT generate_series(1, 19)), 'Peugeot Boxer', FALSE),
('BY1080', ARRAY(SELECT generate_series(1, 20)), 'Fiat Ducato', FALSE),
('BY1081', ARRAY(SELECT generate_series(1, 20)), 'Mercedes Sprinter', FALSE),
('BY1082', ARRAY(SELECT generate_series(1, 18)), 'Ford Transit', FALSE),
('BY1083', ARRAY(SELECT generate_series(1, 22)), 'Volkswagen Crafter', FALSE),
('BY1084', ARRAY(SELECT generate_series(1, 19)), 'Iveco Daily', FALSE),
('BY1085', ARRAY(SELECT generate_series(1, 21)), 'Peugeot Boxer', FALSE),
('BY1086', ARRAY(SELECT generate_series(1, 20)), 'Mercedes Sprinter', FALSE),
('BY1087', ARRAY(SELECT generate_series(1, 17)), 'Fiat Ducato', FALSE),
('BY1088', ARRAY(SELECT generate_series(1, 23)), 'Volkswagen Crafter', FALSE),
('BY2001', ARRAY(SELECT generate_series(1, 20)), 'Mercedes Sprinter', TRUE),
('BY2002', ARRAY(SELECT generate_series(1, 18)), 'Ford Transit', TRUE),
('BY2003', ARRAY(SELECT generate_series(1, 22)), 'Volkswagen Crafter', TRUE),
('BY2004', ARRAY(SELECT generate_series(1, 19)), 'Iveco Daily', TRUE),
('BY2005', ARRAY(SELECT generate_series(1, 21)), 'Peugeot Boxer', TRUE),
('BY2006', ARRAY(SELECT generate_series(1, 20)), 'Mercedes Sprinter', TRUE),
('BY2007', ARRAY(SELECT generate_series(1, 17)), 'Fiat Ducato', TRUE),
('BY2008', ARRAY(SELECT generate_series(1, 23)), 'Volkswagen Crafter', TRUE),
('BY2009', ARRAY(SELECT generate_series(1, 18)), 'Ford Transit', TRUE),
('BY2010', ARRAY(SELECT generate_series(1, 21)), 'Iveco Daily', TRUE),
('BY2011', ARRAY(SELECT generate_series(1, 19)), 'Peugeot Boxer', TRUE),
('BY2012', ARRAY(SELECT generate_series(1, 20)), 'Mercedes Sprinter', TRUE);
            `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('TRUNCATE TABLE Buses');
  }
}
